apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keiko

resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - gateway-deployment.yaml
  - chat-deployment.yaml
  - ingestion-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: keiko

