apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keiko-staging

resources:
  - ../base

replicas:
  - name: frontend
    count: 1
  - name: gateway-bff
    count: 1
  - name: chat-service
    count: 1
  - name: ingestion-service
    count: 1

images:
  - name: keiko/frontend
    newName: acrkeikostaging.azurecr.io/keiko/frontend
  - name: keiko/gateway-bff
    newName: acrkeikostaging.azurecr.io/keiko/gateway-bff
  - name: keiko/chat-service
    newName: acrkeikostaging.azurecr.io/keiko/chat-service
  - name: keiko/ingestion-service
    newName: acrkeikostaging.azurecr.io/keiko/ingestion-service

commonLabels:
  environment: staging

